import { describe, expect, it } from "vitest";

import { renderDecompiledCommandList } from "../src/decompiler.js";

describe("decompiler command list rendering", () => {
  it("renders supported command helpers and deterministic imports from the same command pass", () => {
    expect(
      renderDecompiledCommandList([
        { code: 230, indent: 0, parameters: [30] },
        { code: 117, indent: 0, parameters: [4] },
        { code: 121, indent: 0, parameters: [2, 4, 0] },
        { code: 122, indent: 0, parameters: [3, 5, 1, 3, 3, 1, 0] },
        { code: 122, indent: 0, parameters: [3, 3, 0, 4, "$gameParty.gold()"] },
        { code: 124, indent: 0, parameters: [0, 60] },
        { code: 126, indent: 0, parameters: [5, 1, 0, 2] },
        { code: 127, indent: 0, parameters: [6, 0, 1, 3, true] },
        { code: 128, indent: 0, parameters: [7, 1, 0, 1, false] },
        { code: 129, indent: 0, parameters: [8, 0, true] },
        { code: 132, indent: 0, parameters: [{ name: "Battle1", volume: 80, pitch: 100, pan: 0 }] },
        {
          code: 133,
          indent: 0,
          parameters: [{ name: "Victory1", volume: 90, pitch: 105, pan: 0 }],
        },
        { code: 134, indent: 0, parameters: [0] },
        { code: 135, indent: 0, parameters: [1] },
        { code: 136, indent: 0, parameters: [0] },
        { code: 137, indent: 0, parameters: [0] },
        { code: 138, indent: 0, parameters: [[12, -24, 36, 0]] },
        {
          code: 139,
          indent: 0,
          parameters: [{ name: "Defeat1", volume: 90, pitch: 100, pan: -10 }],
        },
        {
          code: 140,
          indent: 0,
          parameters: [1, { name: "Ship1", volume: 90, pitch: 100, pan: 0 }],
        },
        { code: 201, indent: 0, parameters: [1, 9, 10, 11, 4, 1] },
        { code: 202, indent: 0, parameters: [2, 0, 12, 4, 5] },
        { code: 203, indent: 0, parameters: [0, 0, 6, 7, 8] },
        { code: 203, indent: 0, parameters: [4, 1, 10, 11, 0] },
        { code: 203, indent: 0, parameters: [-1, 2, 0, 0, 0] },
        { code: 204, indent: 0, parameters: [6, 9, 5] },
        {
          code: 205,
          indent: 0,
          parameters: [
            4,
            {
              list: [
                { code: 1, parameters: [] },
                { code: 14, parameters: [2, -1] },
                { code: 15, parameters: [10] },
                { code: 20, parameters: [] },
                { code: 27, parameters: [2] },
                { code: 28, parameters: [3] },
                { code: 29, parameters: [5] },
                { code: 30, parameters: [4] },
                { code: 31, parameters: [] },
                { code: 34, parameters: [] },
                { code: 35, parameters: [] },
                { code: 38, parameters: [] },
                { code: 39, parameters: [] },
                { code: 41, parameters: ["Actor1", 3] },
                { code: 42, parameters: [128] },
                { code: 43, parameters: [1] },
                { code: 44, parameters: [{ name: "Cursor1", volume: 80, pitch: 100, pan: 0 }] },
                { code: 45, parameters: ["this.moveForward();"] },
                { code: 0, parameters: [] },
              ],
              repeat: false,
              skippable: true,
              wait: true,
            },
          ],
        },
        { code: 206, indent: 0, parameters: [] },
        { code: 211, indent: 0, parameters: [0] },
        { code: 212, indent: 0, parameters: [3, 4, true] },
        { code: 213, indent: 0, parameters: [-1, 2, false] },
        { code: 214, indent: 0, parameters: [] },
        { code: 216, indent: 0, parameters: [1] },
        { code: 217, indent: 0, parameters: [] },
        { code: 221, indent: 0, parameters: [] },
        { code: 222, indent: 0, parameters: [] },
        { code: 223, indent: 0, parameters: [[68, -34, -34, 0], 60, true] },
        { code: 224, indent: 0, parameters: [[255, 255, 255, 160], 30, false] },
        { code: 225, indent: 0, parameters: [5, 7, 40, true] },
        { code: 231, indent: 0, parameters: [1, "Poster", 1, 0, 10, 20, 120, 80, 200, 1] },
        { code: 232, indent: 0, parameters: [1, 0, 0, 1, 10, 11, 100, 100, 255, 0, 45, true] },
        { code: 233, indent: 0, parameters: [1, -5] },
        { code: 234, indent: 0, parameters: [1, [0, 0, 0, 255], 30, false] },
        { code: 235, indent: 0, parameters: [1] },
        { code: 236, indent: 0, parameters: ["rain", 6, 50, true] },
        { code: 241, indent: 0, parameters: [{ name: "Theme1", volume: 70, pitch: 100, pan: 0 }] },
        { code: 242, indent: 0, parameters: [45] },
        { code: 243, indent: 0, parameters: [] },
        { code: 244, indent: 0, parameters: [] },
        { code: 245, indent: 0, parameters: [{ name: "Rain", volume: 90, pitch: 90, pan: 0 }] },
        { code: 246, indent: 0, parameters: [30] },
        { code: 249, indent: 0, parameters: [{ name: "Fanfare", volume: 90, pitch: 100, pan: 0 }] },
        { code: 250, indent: 0, parameters: [{ name: "Cursor", volume: 90, pitch: 100, pan: 0 }] },
        { code: 251, indent: 0, parameters: [] },
        { code: 261, indent: 0, parameters: ["Intro"] },
        { code: 281, indent: 0, parameters: [1] },
        { code: 282, indent: 0, parameters: [12] },
        { code: 283, indent: 0, parameters: ["Grassland", "Forest"] },
        { code: 284, indent: 0, parameters: ["Clouds", true, false, 2, 0] },
        { code: 285, indent: 0, parameters: [3, 6, 0, 4, 5] },
        { code: 285, indent: 0, parameters: [5, 3, 1, 10, 11] },
        { code: 0, indent: 0, parameters: [] },
      ]),
    ).toEqual({
      helperNames: [
        "actorRef",
        "animationRef",
        "armorRef",
        "audioAsset",
        "callCommonEvent",
        "changeArmors",
        "changeBattleBack",
        "changeBattleBgm",
        "changeDefeatMe",
        "changeEncounterDisable",
        "changeFormationAccess",
        "changeItems",
        "changeMapNameDisplay",
        "changeMenuAccess",
        "changeParallax",
        "changePartyMember",
        "changePlayerFollowers",
        "changeSaveAccess",
        "changeTileset",
        "changeTransparency",
        "changeVehicleBgm",
        "changeVictoryMe",
        "changeWeapons",
        "changeWindowColor",
        "commonEventRef",
        "controlSwitches",
        "controlTimer",
        "controlVariables",
        "eraseEvent",
        "erasePicture",
        "fadeinScreen",
        "fadeoutBgm",
        "fadeoutBgs",
        "fadeoutScreen",
        "flashScreen",
        "gatherFollowers",
        "getLocationInfo",
        "getOnOffVehicle",
        "imageAsset",
        "itemRef",
        "mapRef",
        "movePicture",
        "movieAsset",
        "playBgm",
        "playBgs",
        "playMe",
        "playMovie",
        "playSe",
        "resumeBgm",
        "rotatePicture",
        "saveBgm",
        "scriptInput",
        "scrollMap",
        "setEventLocation",
        "setMovementRoute",
        "setVehicleLocation",
        "setWeatherEffect",
        "shakeScreen",
        "showAnimation",
        "showBalloonIcon",
        "showPicture",
        "stopSe",
        "switchRef",
        "tilesetRef",
        "tintPicture",
        "tintScreen",
        "transferPlayer",
        "variableRef",
        "wait",
        "weaponRef",
      ],
      source: [
        "wait(30),",
        "callCommonEvent(commonEventRef({ id: 4 })),",
        'controlSwitches({ switch: { kind: "referenceRange", from: switchRef({ id: 2 }), to: switchRef({ id: 4 }) }, value: true }),',
        'controlVariables({ variable: { kind: "referenceRange", from: variableRef({ id: 3 }), to: variableRef({ id: 5 }) }, operation: "add", value: { kind: "gameData", source: "actor", actor: actorRef({ id: 1 }), value: "level" } }),',
        'controlVariables({ variable: variableRef({ id: 3 }), operation: "set", value: { kind: "script", script: scriptInput({ code: "$gameParty.gold()" }) } }),',
        'controlTimer({ action: "start", seconds: 60 }),',
        'changeItems({ item: itemRef({ id: 5 }), operation: "lose", amount: 2 }),',
        'changeWeapons({ weapon: weaponRef({ id: 6 }), operation: "gain", amount: variableRef({ id: 3 }), includeEquipment: true }),',
        'changeArmors({ armor: armorRef({ id: 7 }), operation: "lose", amount: 1, includeEquipment: false }),',
        'changePartyMember({ actor: actorRef({ id: 8 }), operation: "add", initialize: true }),',
        'changeBattleBgm({ audio: { asset: audioAsset({ folder: "bgm", name: "Battle1" }), volume: 80, pitch: 100, pan: 0 } }),',
        'changeVictoryMe({ audio: { asset: audioAsset({ folder: "me", name: "Victory1" }), volume: 90, pitch: 105, pan: 0 } }),',
        "changeSaveAccess({ enabled: false }),",
        "changeMenuAccess({ enabled: true }),",
        "changeEncounterDisable({ disabled: true }),",
        "changeFormationAccess({ enabled: false }),",
        "changeWindowColor({ tone: [12,-24,36,0] }),",
        'changeDefeatMe({ audio: { asset: audioAsset({ folder: "me", name: "Defeat1" }), volume: 90, pitch: 100, pan: -10 } }),',
        'changeVehicleBgm({ vehicle: "ship", audio: { asset: audioAsset({ folder: "bgm", name: "Ship1" }), volume: 90, pitch: 100, pan: 0 } }),',
        'transferPlayer({ destination: { kind: "variables", map: variableRef({ id: 9 }), x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) }, direction: 4, fadeType: 1 }),',
        'setVehicleLocation({ vehicle: "airship", destination: { kind: "direct", map: mapRef({ id: 12 }), x: 4, y: 5 } }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "currentEvent" }, destination: { kind: "direct", x: 6, y: 7 }, direction: 8 }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "event", id: 4 }, destination: { kind: "variables", x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) } }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "player" }, destination: { kind: "exchange", character: { kind: "runtimeSelector", scope: "character", target: "currentEvent" } } }),',
        "scrollMap({ direction: 6, distance: 9, speed: 5 }),",
        'setMovementRoute({ target: { kind: "runtimeSelector", scope: "character", target: "event", id: 4 }, route: [{ kind: "moveDown" }, { kind: "jump", x: 2, y: -1 }, { kind: "routeWait", frames: 10 }, { kind: "turn90Right" }, { kind: "switchOn", switch: switchRef({ id: 2 }) }, { kind: "switchOff", switch: switchRef({ id: 3 }) }, { kind: "changeSpeed", speed: 5 }, { kind: "changeFrequency", frequency: 4 }, { kind: "walkAnimation", enabled: true }, { kind: "stepAnimation", enabled: false }, { kind: "directionFix", enabled: true }, { kind: "through", enabled: false }, { kind: "transparent", enabled: true }, { kind: "changeImage", image: imageAsset({ folder: "characters", name: "Actor1" }), index: 3 }, { kind: "changeOpacity", opacity: 128 }, { kind: "changeBlendMode", blendMode: 1 }, { kind: "playSe", audio: { asset: audioAsset({ folder: "se", name: "Cursor1" }), volume: 80, pitch: 100, pan: 0 } }, { kind: "script", script: scriptInput({ code: "this.moveForward();" }) }], repeat: false, skippable: true, wait: true }),',
        "getOnOffVehicle(),",
        "changeTransparency({ transparent: true }),",
        'showAnimation({ target: { kind: "runtimeSelector", scope: "character", target: "event", id: 3 }, animation: animationRef({ id: 4 }), wait: true }),',
        'showBalloonIcon({ target: { kind: "runtimeSelector", scope: "character", target: "player" }, balloon: "question" }),',
        "eraseEvent(),",
        "changePlayerFollowers({ visible: false }),",
        "gatherFollowers(),",
        "fadeoutScreen(),",
        "fadeinScreen(),",
        "tintScreen({ tone: [68,-34,-34,0], duration: 60, wait: true }),",
        "flashScreen({ color: [255,255,255,160], duration: 30 }),",
        "shakeScreen({ power: 5, speed: 7, duration: 40, wait: true }),",
        'showPicture({ pictureId: 1, image: imageAsset({ folder: "pictures", name: "Poster" }), position: { kind: "direct", x: 10, y: 20, origin: "center" }, scaleX: 120, scaleY: 80, opacity: 200, blendMode: 1 }),',
        'movePicture({ pictureId: 1, position: { kind: "variables", x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) }, duration: 45, wait: true }),',
        "rotatePicture({ pictureId: 1, speed: -5 }),",
        "tintPicture({ pictureId: 1, tone: [0,0,0,255], duration: 30 }),",
        "erasePicture({ pictureId: 1 }),",
        'setWeatherEffect({ weather: "rain", power: 6, duration: 50, wait: true }),',
        'playBgm({ audio: { asset: audioAsset({ folder: "bgm", name: "Theme1" }), volume: 70, pitch: 100, pan: 0 } }),',
        "fadeoutBgm({ duration: 45 }),",
        "saveBgm(),",
        "resumeBgm(),",
        'playBgs({ audio: { asset: audioAsset({ folder: "bgs", name: "Rain" }), volume: 90, pitch: 90, pan: 0 } }),',
        "fadeoutBgs({ duration: 30 }),",
        'playMe({ audio: { asset: audioAsset({ folder: "me", name: "Fanfare" }), volume: 90, pitch: 100, pan: 0 } }),',
        'playSe({ audio: { asset: audioAsset({ folder: "se", name: "Cursor" }), volume: 90, pitch: 100, pan: 0 } }),',
        "stopSe(),",
        'playMovie({ movie: movieAsset({ name: "Intro" }) }),',
        "changeMapNameDisplay({ enabled: false }),",
        "changeTileset({ tileset: tilesetRef({ id: 12 }) }),",
        'changeBattleBack({ battleback1: imageAsset({ folder: "battlebacks1", name: "Grassland" }), battleback2: imageAsset({ folder: "battlebacks2", name: "Forest" }) }),',
        'changeParallax({ image: imageAsset({ folder: "parallaxes", name: "Clouds" }), loopX: true, sx: 2 }),',
        'getLocationInfo({ variable: variableRef({ id: 3 }), info: "regionId", location: { kind: "direct", x: 4, y: 5 } }),',
        'getLocationInfo({ variable: variableRef({ id: 5 }), info: "tileIdLayer2", location: { kind: "variables", x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) } }),',
      ].join("\n"),
    });
  });

  it("renders text and comment continuations as parent-owned helpers", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["", 0, 0, 2] },
        { code: 401, indent: 0, parameters: ["Hello"] },
        { code: 401, indent: 0, parameters: ["World"] },
        { code: 401, indent: 1, parameters: ["Different indent stays raw"] },
        { code: 108, indent: 0, parameters: ["First"] },
        { code: 408, indent: 0, parameters: ["Second"] },
      ]),
    ).toEqual({
      helperNames: ["comment", "rawDslCommand", "showText"],
      source: [
        'showText({ lines: ["Hello","World"] }),',
        "rawDslCommand({",
        "  code: 401,",
        "  indent: 1,",
        '  parameters: ["Different indent stays raw"],',
        "}),",
        'comment(["First","Second"]),',
      ].join("\n"),
    });
  });

  it("renders message commands and continuations as supported helpers", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["Actor1", 2, 1, 0] },
        { code: 401, indent: 0, parameters: ["Hello"] },
        { code: 102, indent: 0, parameters: [["Yes", "No"], 1, 0, 2, 0] },
        { code: 402, indent: 0, parameters: [0] },
        { code: 230, indent: 1, parameters: [10] },
        { code: 402, indent: 0, parameters: [1] },
        { code: 214, indent: 1, parameters: [] },
        { code: 403, indent: 0, parameters: [] },
        { code: 101, indent: 1, parameters: ["", 0, 0, 2] },
        { code: 401, indent: 1, parameters: ["Canceled"] },
        { code: 103, indent: 0, parameters: [3, 4] },
        { code: 104, indent: 0, parameters: [3, 1] },
        { code: 105, indent: 0, parameters: [5, true] },
        { code: 405, indent: 0, parameters: ["Scroll"] },
        { code: 405, indent: 0, parameters: ["More"] },
      ]),
    ).toEqual({
      helperNames: [
        "eraseEvent",
        "imageAsset",
        "inputNumber",
        "selectItem",
        "showChoices",
        "showScrollingText",
        "showText",
        "variableRef",
        "wait",
      ],
      source: [
        'showText({ lines: ["Hello"], face: { image: imageAsset({ folder: "faces", name: "Actor1" }), index: 2 }, background: 1, positionType: 0 }),',
        'showChoices({ choices: ["Yes","No"], branches: [[wait(10),], [eraseEvent(),]], cancelType: 1, cancelBranch: [showText({ lines: ["Canceled"] }),] }),',
        "inputNumber({ variable: variableRef({ id: 3 }), digits: 4 }),",
        "selectItem({ variable: variableRef({ id: 3 }), itemType: 1 }),",
        'showScrollingText({ lines: ["Scroll","More"], speed: 5, noFastForward: true }),',
      ].join("\n"),
    });
  });

  it("renders Conditional Branch continuations as a parent-owned helper", () => {
    expect(
      renderDecompiledCommandList([
        { code: 111, indent: 0, parameters: [0, 2, 0] },
        { code: 230, indent: 1, parameters: [10] },
        { code: 411, indent: 0, parameters: [] },
        { code: 111, indent: 1, parameters: [12, "$gameParty.gold() > 10"] },
        { code: 214, indent: 2, parameters: [] },
        { code: 230, indent: 0, parameters: [30] },
      ]),
    ).toEqual({
      helperNames: ["conditional", "eraseEvent", "scriptInput", "switchRef", "wait"],
      source: [
        'conditional({ condition: { kind: "switch", switch: switchRef({ id: 2 }), value: true }, then: [wait(10),], else: [conditional({ condition: {   kind: "script",   script: scriptInput({ code: "$gameParty.gold() > 10" }), }, then: [eraseEvent(),] }),] }),',
        "wait(30),",
      ].join("\n"),
    });
  });

  it("renders supported Conditional Branch condition categories", () => {
    expect(
      renderDecompiledCommandList([
        { code: 111, indent: 0, parameters: [1, 3, 1, 4, 5] },
        { code: 111, indent: 0, parameters: [4, 1, 2, 5] },
        { code: 111, indent: 0, parameters: [5, 0, 1, 6] },
        { code: 111, indent: 0, parameters: [9, 7, true] },
        { code: 111, indent: 0, parameters: [13, 2] },
      ]),
    ).toEqual({
      helperNames: ["actorRef", "classRef", "conditional", "stateRef", "variableRef", "weaponRef"],
      source: [
        'conditional({ condition: { kind: "variable", variable: variableRef({ id: 3 }), operator: "ne", value: variableRef({ id: 4 }) }, then: [] }),',
        'conditional({ condition: { kind: "actor", actor: actorRef({ id: 1 }), check: { kind: "class", class: classRef({ id: 5 }) } }, then: [] }),',
        'conditional({ condition: { kind: "enemy", enemyIndex: 0, check: { kind: "state", state: stateRef({ id: 6 }) } }, then: [] }),',
        'conditional({ condition: { kind: "weapon", weapon: weaponRef({ id: 7 }), includeEquipment: true }, then: [] }),',
        'conditional({ condition: { kind: "vehicle", vehicle: "airship" }, then: [] }),',
      ].join("\n"),
    });
  });

  it("renders Scene Control, Actor, Enemy, Advanced, and continuation commands", () => {
    expect(
      renderDecompiledCommandList([
        { code: 301, indent: 0, parameters: [1, 2, true, true] },
        { code: 601, indent: 0, parameters: [] },
        { code: 230, indent: 1, parameters: [1] },
        { code: 602, indent: 0, parameters: [] },
        { code: 230, indent: 1, parameters: [2] },
        { code: 603, indent: 0, parameters: [] },
        { code: 230, indent: 1, parameters: [3] },
        { code: 302, indent: 0, parameters: [0, 1, 0, 0, true] },
        { code: 605, indent: 0, parameters: [1, 2, 1, 250] },
        { code: 303, indent: 0, parameters: [1, 8] },
        { code: 311, indent: 0, parameters: [0, 0, 1, 0, 10, true] },
        { code: 312, indent: 0, parameters: [1, 2, 0, 1, 3] },
        { code: 313, indent: 0, parameters: [0, 1, 0, 4] },
        { code: 314, indent: 0, parameters: [0, 0] },
        { code: 315, indent: 0, parameters: [0, 1, 0, 0, 50, true] },
        { code: 316, indent: 0, parameters: [0, 1, 1, 0, 1, false] },
        { code: 317, indent: 0, parameters: [0, 1, 2, 0, 0, 2] },
        { code: 318, indent: 0, parameters: [0, 1, 0, 5] },
        { code: 319, indent: 0, parameters: [1, 1, 6] },
        { code: 320, indent: 0, parameters: [1, "Alex"] },
        { code: 321, indent: 0, parameters: [1, 7, true] },
        { code: 322, indent: 0, parameters: [1, "Actor1", 0, "Actor1", 1, "Actor1_1"] },
        { code: 323, indent: 0, parameters: [0, "Vehicle", 2] },
        { code: 324, indent: 0, parameters: [1, "Ace"] },
        { code: 325, indent: 0, parameters: [1, "Profile"] },
        { code: 326, indent: 0, parameters: [0, 1, 0, 0, 5] },
        { code: 331, indent: 0, parameters: [-1, 1, 0, 10, true] },
        { code: 332, indent: 0, parameters: [0, 0, 1, 3] },
        { code: 333, indent: 0, parameters: [0, 1, 4] },
        { code: 334, indent: 0, parameters: [0] },
        { code: 335, indent: 0, parameters: [0] },
        { code: 336, indent: 0, parameters: [0, 8] },
        { code: 337, indent: 0, parameters: [0, 9, true] },
        { code: 339, indent: 0, parameters: [1, 1, 5, -2] },
        { code: 340, indent: 0, parameters: [] },
        { code: 342, indent: 0, parameters: [0, 0, 0, 4] },
        { code: 351, indent: 0, parameters: [] },
        { code: 352, indent: 0, parameters: [] },
        { code: 353, indent: 0, parameters: [] },
        { code: 354, indent: 0, parameters: [] },
        { code: 355, indent: 0, parameters: ["const x = 1;"] },
        { code: 655, indent: 0, parameters: ["console.log(x);"] },
        { code: 356, indent: 0, parameters: ["MyPlugin arg1 arg2"] },
      ]),
    ).toEqual({
      helperNames: [
        "abortBattle",
        "actorRef",
        "animationRef",
        "battleProcessing",
        "changeActorImages",
        "changeClass",
        "changeEnemyHp",
        "changeEnemyMp",
        "changeEnemyState",
        "changeEnemyTp",
        "changeEquipment",
        "changeExp",
        "changeHp",
        "changeLevel",
        "changeMp",
        "changeName",
        "changeNickname",
        "changeParameter",
        "changeProfile",
        "changeSkill",
        "changeState",
        "changeTp",
        "changeVehicleImage",
        "classRef",
        "enemyAppear",
        "enemyRecoverAll",
        "enemyRef",
        "enemyTransform",
        "forceAction",
        "gameOver",
        "imageAsset",
        "itemRef",
        "nameInputProcessing",
        "openMenuScreen",
        "openSaveScreen",
        "pluginCommand",
        "recoverAll",
        "returnToTitleScreen",
        "script",
        "shopProcessing",
        "showBattleAnimation",
        "skillRef",
        "stateRef",
        "variableRef",
        "wait",
        "weaponRef",
      ],
      source: [
        'battleProcessing({ troop: { kind: "troop", variable: variableRef({ id: 2 }) }, canEscape: true, canLose: true, win: [wait(1),], escape: [wait(2),], lose: [wait(3),] }),',
        'shopProcessing({ goods: [{ kind: "item", item: itemRef({ id: 1 }) }, { kind: "weapon", item: weaponRef({ id: 2 }), price: 250 }], allowSelling: true }),',
        "nameInputProcessing({ actor: actorRef({ id: 1 }), maxCharacters: 8 }),",
        'changeHp({ target: { kind: "runtimeSelector", scope: "actor", target: "entireParty" }, operation: "lose", value: 10, allowDeath: true }),',
        'changeMp({ target: { kind: "runtimeSelector", scope: "actor", target: "actorFromVariable", variable: variableRef({ id: 2 }) }, operation: "gain", value: variableRef({ id: 3 }) }),',
        'changeState({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, operation: "add", state: stateRef({ id: 4 }) }),',
        'recoverAll({ target: { kind: "runtimeSelector", scope: "actor", target: "entireParty" } }),',
        'changeExp({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, operation: "gain", value: 50, showLevelUp: true }),',
        'changeLevel({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, operation: "lose", value: 1 }),',
        'changeParameter({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, parameter: "atk", operation: "gain", value: 2 }),',
        'changeSkill({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, operation: "learn", skill: skillRef({ id: 5 }) }),',
        "changeEquipment({ actor: actorRef({ id: 1 }), equipmentTypeId: 1, itemId: 6 }),",
        'changeName({ actor: actorRef({ id: 1 }), name: "Alex" }),',
        "changeClass({ actor: actorRef({ id: 1 }), class: classRef({ id: 7 }), keepExp: true }),",
        'changeActorImages({ actor: actorRef({ id: 1 }), character: { image: imageAsset({ folder: "characters", name: "Actor1" }), index: 0 }, face: { image: imageAsset({ folder: "faces", name: "Actor1" }), index: 1 }, battler: imageAsset({ folder: "sv_actors", name: "Actor1_1" }) }),',
        'changeVehicleImage({ vehicle: "boat", image: imageAsset({ folder: "characters", name: "Vehicle" }), index: 2 }),',
        'changeNickname({ actor: actorRef({ id: 1 }), nickname: "Ace" }),',
        'changeProfile({ actor: actorRef({ id: 1 }), profile: "Profile" }),',
        'changeTp({ target: { kind: "runtimeSelector", scope: "actor", target: "actor", actorId: 1 }, operation: "gain", value: 5 }),',
        'changeEnemyHp({ target: { kind: "runtimeSelector", scope: "enemy", target: "all" }, operation: "lose", value: 10, allowDeath: true }),',
        'changeEnemyMp({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 }, operation: "gain", value: variableRef({ id: 3 }) }),',
        'changeEnemyState({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 }, operation: "remove", state: stateRef({ id: 4 }) }),',
        'enemyRecoverAll({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 } }),',
        'enemyAppear({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 } }),',
        'enemyTransform({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 }, enemy: enemyRef({ id: 8 }) }),',
        'showBattleAnimation({ target: { kind: "runtimeSelector", scope: "enemy", target: "all" }, animation: animationRef({ id: 9 }) }),',
        'forceAction({ subject: { kind: "runtimeSelector", scope: "battler", target: "actor", actorId: 1 }, skill: skillRef({ id: 5 }), targetIndex: -2 }),',
        "abortBattle(),",
        'changeEnemyTp({ target: { kind: "runtimeSelector", scope: "enemy", target: "enemy", index: 0 }, operation: "gain", value: 4 }),',
        "openMenuScreen(),",
        "openSaveScreen(),",
        "gameOver(),",
        "returnToTitleScreen(),",
        'script({ code: "const x = 1;\\nconsole.log(x);" }),',
        'pluginCommand({ command: "MyPlugin", args: ["arg1","arg2"] }),',
      ].join("\n"),
    });
  });

  it("falls back to rawDslCommand for malformed supported command shapes", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["Actor1", 0, 9, 2] },
        { code: 102, indent: 0, parameters: [["Yes"], -1, 0, 9, 0] },
        { code: 103, indent: 0, parameters: [0, 4] },
        { code: 104, indent: 0, parameters: [1, 9] },
        { code: 105, indent: 0, parameters: [2, "false"] },
        { code: 111, indent: 0, parameters: [1, 0, 0, 7, 0] },
        { code: 122, indent: 0, parameters: [1, 1, 99, 0, 7] },
        { code: 124, indent: 0, parameters: [0, "60"] },
        { code: 201, indent: 0, parameters: [1, 0, 2, 3, 2, 0] },
        { code: 202, indent: 0, parameters: [3, 0, 1, 2, 3] },
        { code: 203, indent: 0, parameters: [0, 2, -2, 0, 0] },
        { code: 204, indent: 0, parameters: [1, 9, 5] },
        {
          code: 205,
          indent: 0,
          parameters: [
            0,
            {
              list: [{ code: 45, parameters: [123] }],
              repeat: true,
              skippable: false,
              wait: false,
            },
          ],
        },
        { code: 211, indent: 0, parameters: [2] },
        { code: 212, indent: 0, parameters: [0, 0, true] },
        { code: 213, indent: 0, parameters: [0, 0, true] },
        { code: 223, indent: 0, parameters: [[0, 0, 0], 30, true] },
        { code: 224, indent: 0, parameters: [[255, 255, 255, "bad"], 30, false] },
        { code: 225, indent: 0, parameters: [5, 7, "40", true] },
        { code: 231, indent: 0, parameters: [1, "Poster", 0, 1, 0, 2, 100, 100, 255, 0] },
        { code: 232, indent: 0, parameters: [1, 0, 0, 0, 10, 20, 100, 100, 255, 9, 45, true] },
        { code: 233, indent: 0, parameters: [0, 5] },
        { code: 234, indent: 0, parameters: [1, [0, 0, 0, 0], "30", false] },
        { code: 235, indent: 0, parameters: [0] },
        { code: 236, indent: 0, parameters: ["hail", 6, 50, true] },
        { code: 127, indent: 0, parameters: [1, 0, 0, 1, "false"] },
        { code: 129, indent: 0, parameters: [1, 2, false] },
        { code: 356, indent: 0, parameters: ["Plugin  keeps  spaces"] },
        { code: 230, indent: 2, parameters: ["thirty"] },
      ]),
    ).toEqual({
      helperNames: ["rawDslCommand"],
      source: [
        "rawDslCommand({",
        "  code: 101,",
        '  parameters: ["Actor1",0,9,2],',
        "}),",
        "rawDslCommand({",
        "  code: 102,",
        '  parameters: [["Yes"],-1,0,9,0],',
        "}),",
        "rawDslCommand({",
        "  code: 103,",
        "  parameters: [0,4],",
        "}),",
        "rawDslCommand({",
        "  code: 104,",
        "  parameters: [1,9],",
        "}),",
        "rawDslCommand({",
        "  code: 105,",
        '  parameters: [2,"false"],',
        "}),",
        "rawDslCommand({",
        "  code: 111,",
        "  parameters: [1,0,0,7,0],",
        "}),",
        "rawDslCommand({",
        "  code: 122,",
        "  parameters: [1,1,99,0,7],",
        "}),",
        "rawDslCommand({",
        "  code: 124,",
        '  parameters: [0,"60"],',
        "}),",
        "rawDslCommand({",
        "  code: 201,",
        "  parameters: [1,0,2,3,2,0],",
        "}),",
        "rawDslCommand({",
        "  code: 202,",
        "  parameters: [3,0,1,2,3],",
        "}),",
        "rawDslCommand({",
        "  code: 203,",
        "  parameters: [0,2,-2,0,0],",
        "}),",
        "rawDslCommand({",
        "  code: 204,",
        "  parameters: [1,9,5],",
        "}),",
        "rawDslCommand({",
        "  code: 205,",
        '  parameters: [0,{"list":[{"code":45,"parameters":[123]}],"repeat":true,"skippable":false,"wait":false}],',
        "}),",
        "rawDslCommand({",
        "  code: 211,",
        "  parameters: [2],",
        "}),",
        "rawDslCommand({",
        "  code: 212,",
        "  parameters: [0,0,true],",
        "}),",
        "rawDslCommand({",
        "  code: 213,",
        "  parameters: [0,0,true],",
        "}),",
        "rawDslCommand({",
        "  code: 223,",
        "  parameters: [[0,0,0],30,true],",
        "}),",
        "rawDslCommand({",
        "  code: 224,",
        '  parameters: [[255,255,255,"bad"],30,false],',
        "}),",
        "rawDslCommand({",
        "  code: 225,",
        '  parameters: [5,7,"40",true],',
        "}),",
        "rawDslCommand({",
        "  code: 231,",
        '  parameters: [1,"Poster",0,1,0,2,100,100,255,0],',
        "}),",
        "rawDslCommand({",
        "  code: 232,",
        "  parameters: [1,0,0,0,10,20,100,100,255,9,45,true],",
        "}),",
        "rawDslCommand({",
        "  code: 233,",
        "  parameters: [0,5],",
        "}),",
        "rawDslCommand({",
        "  code: 234,",
        '  parameters: [1,[0,0,0,0],"30",false],',
        "}),",
        "rawDslCommand({",
        "  code: 235,",
        "  parameters: [0],",
        "}),",
        "rawDslCommand({",
        "  code: 236,",
        '  parameters: ["hail",6,50,true],',
        "}),",
        "rawDslCommand({",
        "  code: 127,",
        '  parameters: [1,0,0,1,"false"],',
        "}),",
        "rawDslCommand({",
        "  code: 129,",
        "  parameters: [1,2,false],",
        "}),",
        "rawDslCommand({",
        "  code: 356,",
        '  parameters: ["Plugin  keeps  spaces"],',
        "}),",
        "rawDslCommand({",
        "  code: 230,",
        "  indent: 2,",
        '  parameters: ["thirty"],',
        "}),",
      ].join("\n"),
    });
  });
});
