import { describe, expect, it } from "vitest";

import { renderDecompiledCommandList } from "../src/decompiler.js";

describe("decompiler command list rendering", () => {
  it("renders supported command helpers and deterministic imports from the same command pass", () => {
    expect(
      renderDecompiledCommandList([
        { code: 230, indent: 0, parameters: [30] },
        { code: 117, indent: 0, parameters: [4] },
        { code: 121, indent: 0, parameters: [2, 4, 0] },
        { code: 122, indent: 0, parameters: [3, 5, 1, 3, 3, 1, 0] },
        { code: 122, indent: 0, parameters: [3, 3, 0, 4, "$gameParty.gold()"] },
        { code: 124, indent: 0, parameters: [0, 60] },
        { code: 126, indent: 0, parameters: [5, 1, 0, 2] },
        { code: 127, indent: 0, parameters: [6, 0, 1, 3, true] },
        { code: 128, indent: 0, parameters: [7, 1, 0, 1, false] },
        { code: 129, indent: 0, parameters: [8, 0, true] },
        { code: 201, indent: 0, parameters: [1, 9, 10, 11, 4, 1] },
        { code: 202, indent: 0, parameters: [2, 0, 12, 4, 5] },
        { code: 203, indent: 0, parameters: [0, 0, 6, 7, 8] },
        { code: 203, indent: 0, parameters: [4, 1, 10, 11, 0] },
        { code: 203, indent: 0, parameters: [-1, 2, 0, 0, 0] },
        { code: 204, indent: 0, parameters: [6, 9, 5] },
        {
          code: 205,
          indent: 0,
          parameters: [
            4,
            {
              list: [
                { code: 1, parameters: [] },
                { code: 14, parameters: [2, -1] },
                { code: 15, parameters: [10] },
                { code: 20, parameters: [] },
                { code: 27, parameters: [2] },
                { code: 28, parameters: [3] },
                { code: 29, parameters: [5] },
                { code: 30, parameters: [4] },
                { code: 31, parameters: [] },
                { code: 34, parameters: [] },
                { code: 35, parameters: [] },
                { code: 38, parameters: [] },
                { code: 39, parameters: [] },
                { code: 41, parameters: ["Actor1", 3] },
                { code: 42, parameters: [128] },
                { code: 43, parameters: [1] },
                { code: 44, parameters: [{ name: "Cursor1", volume: 80, pitch: 100, pan: 0 }] },
                { code: 45, parameters: ["this.moveForward();"] },
                { code: 0, parameters: [] },
              ],
              repeat: false,
              skippable: true,
              wait: true,
            },
          ],
        },
        { code: 206, indent: 0, parameters: [] },
        { code: 214, indent: 0, parameters: [] },
        { code: 0, indent: 0, parameters: [] },
      ]),
    ).toEqual({
      helperNames: [
        "actorRef",
        "armorRef",
        "audioAsset",
        "callCommonEvent",
        "changeArmors",
        "changeItems",
        "changePartyMember",
        "changeWeapons",
        "commonEventRef",
        "controlSwitches",
        "controlTimer",
        "controlVariables",
        "eraseEvent",
        "getOnOffVehicle",
        "imageAsset",
        "itemRef",
        "mapRef",
        "scriptInput",
        "scrollMap",
        "setEventLocation",
        "setMovementRoute",
        "setVehicleLocation",
        "switchRef",
        "transferPlayer",
        "variableRef",
        "wait",
        "weaponRef",
      ],
      source: [
        "wait(30),",
        "callCommonEvent(commonEventRef({ id: 4 })),",
        'controlSwitches({ switch: { kind: "referenceRange", from: switchRef({ id: 2 }), to: switchRef({ id: 4 }) }, value: true }),',
        'controlVariables({ variable: { kind: "referenceRange", from: variableRef({ id: 3 }), to: variableRef({ id: 5 }) }, operation: "add", value: { kind: "gameData", source: "actor", actor: actorRef({ id: 1 }), value: "level" } }),',
        'controlVariables({ variable: variableRef({ id: 3 }), operation: "set", value: { kind: "script", script: scriptInput({ code: "$gameParty.gold()" }) } }),',
        'controlTimer({ action: "start", seconds: 60 }),',
        'changeItems({ item: itemRef({ id: 5 }), operation: "lose", amount: 2 }),',
        'changeWeapons({ weapon: weaponRef({ id: 6 }), operation: "gain", amount: variableRef({ id: 3 }), includeEquipment: true }),',
        'changeArmors({ armor: armorRef({ id: 7 }), operation: "lose", amount: 1, includeEquipment: false }),',
        'changePartyMember({ actor: actorRef({ id: 8 }), operation: "add", initialize: true }),',
        'transferPlayer({ destination: { kind: "variables", map: variableRef({ id: 9 }), x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) }, direction: 4, fadeType: 1 }),',
        'setVehicleLocation({ vehicle: "airship", destination: { kind: "direct", map: mapRef({ id: 12 }), x: 4, y: 5 } }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "currentEvent" }, destination: { kind: "direct", x: 6, y: 7 }, direction: 8 }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "event", id: 4 }, destination: { kind: "variables", x: variableRef({ id: 10 }), y: variableRef({ id: 11 }) } }),',
        'setEventLocation({ character: { kind: "runtimeSelector", scope: "character", target: "player" }, destination: { kind: "exchange", character: { kind: "runtimeSelector", scope: "character", target: "currentEvent" } } }),',
        "scrollMap({ direction: 6, distance: 9, speed: 5 }),",
        'setMovementRoute({ target: { kind: "runtimeSelector", scope: "character", target: "event", id: 4 }, route: [{ kind: "moveDown" }, { kind: "jump", x: 2, y: -1 }, { kind: "routeWait", frames: 10 }, { kind: "turn90Right" }, { kind: "switchOn", switch: switchRef({ id: 2 }) }, { kind: "switchOff", switch: switchRef({ id: 3 }) }, { kind: "changeSpeed", speed: 5 }, { kind: "changeFrequency", frequency: 4 }, { kind: "walkAnimation", enabled: true }, { kind: "stepAnimation", enabled: false }, { kind: "directionFix", enabled: true }, { kind: "through", enabled: false }, { kind: "transparent", enabled: true }, { kind: "changeImage", image: imageAsset({ folder: "characters", name: "Actor1" }), index: 3 }, { kind: "changeOpacity", opacity: 128 }, { kind: "changeBlendMode", blendMode: 1 }, { kind: "playSe", audio: { asset: audioAsset({ folder: "se", name: "Cursor1" }), volume: 80, pitch: 100, pan: 0 } }, { kind: "script", script: scriptInput({ code: "this.moveForward();" }) }], repeat: false, skippable: true, wait: true }),',
        "getOnOffVehicle(),",
        "eraseEvent(),",
      ].join("\n"),
    });
  });

  it("renders text and comment continuations as parent-owned helpers", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["", 0, 0, 2] },
        { code: 401, indent: 0, parameters: ["Hello"] },
        { code: 401, indent: 0, parameters: ["World"] },
        { code: 401, indent: 1, parameters: ["Different indent stays raw"] },
        { code: 108, indent: 0, parameters: ["First"] },
        { code: 408, indent: 0, parameters: ["Second"] },
      ]),
    ).toEqual({
      helperNames: ["comment", "rawDslCommand", "showText"],
      source: [
        'showText({ lines: ["Hello","World"] }),',
        "rawDslCommand({",
        "  code: 401,",
        "  indent: 1,",
        '  parameters: ["Different indent stays raw"],',
        "}),",
        'comment(["First","Second"]),',
      ].join("\n"),
    });
  });

  it("renders message commands and continuations as supported helpers", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["Actor1", 2, 1, 0] },
        { code: 401, indent: 0, parameters: ["Hello"] },
        { code: 102, indent: 0, parameters: [["Yes", "No"], 1, 0, 2, 0] },
        { code: 402, indent: 0, parameters: [0] },
        { code: 230, indent: 1, parameters: [10] },
        { code: 402, indent: 0, parameters: [1] },
        { code: 214, indent: 1, parameters: [] },
        { code: 403, indent: 0, parameters: [] },
        { code: 101, indent: 1, parameters: ["", 0, 0, 2] },
        { code: 401, indent: 1, parameters: ["Canceled"] },
        { code: 103, indent: 0, parameters: [3, 4] },
        { code: 104, indent: 0, parameters: [3, 1] },
        { code: 105, indent: 0, parameters: [5, true] },
        { code: 405, indent: 0, parameters: ["Scroll"] },
        { code: 405, indent: 0, parameters: ["More"] },
      ]),
    ).toEqual({
      helperNames: [
        "eraseEvent",
        "imageAsset",
        "inputNumber",
        "selectItem",
        "showChoices",
        "showScrollingText",
        "showText",
        "variableRef",
        "wait",
      ],
      source: [
        'showText({ lines: ["Hello"], face: { image: imageAsset({ folder: "faces", name: "Actor1" }), index: 2 }, background: 1, positionType: 0 }),',
        'showChoices({ choices: ["Yes","No"], branches: [[wait(10),], [eraseEvent(),]], cancelType: 1, cancelBranch: [showText({ lines: ["Canceled"] }),] }),',
        "inputNumber({ variable: variableRef({ id: 3 }), digits: 4 }),",
        "selectItem({ variable: variableRef({ id: 3 }), itemType: 1 }),",
        'showScrollingText({ lines: ["Scroll","More"], speed: 5, noFastForward: true }),',
      ].join("\n"),
    });
  });

  it("renders Conditional Branch continuations as a parent-owned helper", () => {
    expect(
      renderDecompiledCommandList([
        { code: 111, indent: 0, parameters: [0, 2, 0] },
        { code: 230, indent: 1, parameters: [10] },
        { code: 411, indent: 0, parameters: [] },
        { code: 111, indent: 1, parameters: [12, "$gameParty.gold() > 10"] },
        { code: 214, indent: 2, parameters: [] },
        { code: 230, indent: 0, parameters: [30] },
      ]),
    ).toEqual({
      helperNames: ["conditional", "eraseEvent", "scriptInput", "switchRef", "wait"],
      source: [
        'conditional({ condition: { kind: "switch", switch: switchRef({ id: 2 }), value: true }, then: [wait(10),], else: [conditional({ condition: {   kind: "script",   script: scriptInput({ code: "$gameParty.gold() > 10" }), }, then: [eraseEvent(),] }),] }),',
        "wait(30),",
      ].join("\n"),
    });
  });

  it("renders supported Conditional Branch condition categories", () => {
    expect(
      renderDecompiledCommandList([
        { code: 111, indent: 0, parameters: [1, 3, 1, 4, 5] },
        { code: 111, indent: 0, parameters: [4, 1, 2, 5] },
        { code: 111, indent: 0, parameters: [5, 0, 1, 6] },
        { code: 111, indent: 0, parameters: [9, 7, true] },
        { code: 111, indent: 0, parameters: [13, 2] },
      ]),
    ).toEqual({
      helperNames: ["actorRef", "classRef", "conditional", "stateRef", "variableRef", "weaponRef"],
      source: [
        'conditional({ condition: { kind: "variable", variable: variableRef({ id: 3 }), operator: "ne", value: variableRef({ id: 4 }) }, then: [] }),',
        'conditional({ condition: { kind: "actor", actor: actorRef({ id: 1 }), check: { kind: "class", class: classRef({ id: 5 }) } }, then: [] }),',
        'conditional({ condition: { kind: "enemy", enemyIndex: 0, check: { kind: "state", state: stateRef({ id: 6 }) } }, then: [] }),',
        'conditional({ condition: { kind: "weapon", weapon: weaponRef({ id: 7 }), includeEquipment: true }, then: [] }),',
        'conditional({ condition: { kind: "vehicle", vehicle: "airship" }, then: [] }),',
      ].join("\n"),
    });
  });

  it("falls back to rawDslCommand for malformed supported command shapes", () => {
    expect(
      renderDecompiledCommandList([
        { code: 101, indent: 0, parameters: ["Actor1", 0, 9, 2] },
        { code: 102, indent: 0, parameters: [["Yes"], -1, 0, 9, 0] },
        { code: 103, indent: 0, parameters: [0, 4] },
        { code: 104, indent: 0, parameters: [1, 9] },
        { code: 105, indent: 0, parameters: [2, "false"] },
        { code: 111, indent: 0, parameters: [1, 0, 0, 7, 0] },
        { code: 122, indent: 0, parameters: [1, 1, 99, 0, 7] },
        { code: 124, indent: 0, parameters: [0, "60"] },
        { code: 201, indent: 0, parameters: [1, 0, 2, 3, 2, 0] },
        { code: 202, indent: 0, parameters: [3, 0, 1, 2, 3] },
        { code: 203, indent: 0, parameters: [0, 2, -2, 0, 0] },
        { code: 204, indent: 0, parameters: [1, 9, 5] },
        {
          code: 205,
          indent: 0,
          parameters: [
            0,
            {
              list: [{ code: 45, parameters: [123] }],
              repeat: true,
              skippable: false,
              wait: false,
            },
          ],
        },
        { code: 127, indent: 0, parameters: [1, 0, 0, 1, "false"] },
        { code: 129, indent: 0, parameters: [1, 2, false] },
        { code: 230, indent: 2, parameters: ["thirty"] },
      ]),
    ).toEqual({
      helperNames: ["rawDslCommand"],
      source: [
        "rawDslCommand({",
        "  code: 101,",
        '  parameters: ["Actor1",0,9,2],',
        "}),",
        "rawDslCommand({",
        "  code: 102,",
        '  parameters: [["Yes"],-1,0,9,0],',
        "}),",
        "rawDslCommand({",
        "  code: 103,",
        "  parameters: [0,4],",
        "}),",
        "rawDslCommand({",
        "  code: 104,",
        "  parameters: [1,9],",
        "}),",
        "rawDslCommand({",
        "  code: 105,",
        '  parameters: [2,"false"],',
        "}),",
        "rawDslCommand({",
        "  code: 111,",
        "  parameters: [1,0,0,7,0],",
        "}),",
        "rawDslCommand({",
        "  code: 122,",
        "  parameters: [1,1,99,0,7],",
        "}),",
        "rawDslCommand({",
        "  code: 124,",
        '  parameters: [0,"60"],',
        "}),",
        "rawDslCommand({",
        "  code: 201,",
        "  parameters: [1,0,2,3,2,0],",
        "}),",
        "rawDslCommand({",
        "  code: 202,",
        "  parameters: [3,0,1,2,3],",
        "}),",
        "rawDslCommand({",
        "  code: 203,",
        "  parameters: [0,2,-2,0,0],",
        "}),",
        "rawDslCommand({",
        "  code: 204,",
        "  parameters: [1,9,5],",
        "}),",
        "rawDslCommand({",
        "  code: 205,",
        '  parameters: [0,{"list":[{"code":45,"parameters":[123]}],"repeat":true,"skippable":false,"wait":false}],',
        "}),",
        "rawDslCommand({",
        "  code: 127,",
        '  parameters: [1,0,0,1,"false"],',
        "}),",
        "rawDslCommand({",
        "  code: 129,",
        "  parameters: [1,2,false],",
        "}),",
        "rawDslCommand({",
        "  code: 230,",
        "  indent: 2,",
        '  parameters: ["thirty"],',
        "}),",
      ].join("\n"),
    });
  });
});
