export const runtimeBaseline = {
  language: "typescript-strict",
  moduleSystem: "esm-nodenext",
  packageManager: "pnpm",
  runtime: "node-22-lts",
} as const;

export { loadWorkspace } from "./workspace.js";
export { loadDefinitionFile } from "./definitions.js";
export {
  cloneWorkspace,
  compileWorkspace,
  decompileWorkspace,
  diffWorkspace,
  isGeneratedProjectDataFresh,
  pullWorkspace,
  pushWorkspace,
} from "./workflow.js";
export {
  buildDuplicateAwareNameIndex,
  buildSnapshotReferenceInput,
  buildStagedDataGraph,
  validateDslOwnedDeclarations,
  validateStagedDataGraph,
} from "./staged-graph.js";
export {
  actorRef,
  animationRef,
  audioAsset,
  armorRef,
  breakLoop,
  battleProcessing,
  changeArmors,
  changeGold,
  changeItems,
  changePartyMember,
  changePlayerFollowers,
  changeTransparency,
  changeWeapons,
  classRef,
  comment,
  commonEvent,
  callCommonEvent,
  collectDslOwnedDeclarations,
  commonEventRef,
  controlSelfSwitch,
  controlSwitches,
  controlTimer,
  controlVariables,
  erasePicture,
  eraseEvent,
  conditional,
  exitEvent,
  fadeinScreen,
  fadeoutScreen,
  flashScreen,
  gatherFollowers,
  getOnOffVehicle,
  imageAsset,
  inputNumber,
  itemRef,
  jumpToLabel,
  label,
  loop,
  mapEvent,
  mapRef,
  page,
  pluginCommand,
  movieAsset,
  movePicture,
  rawDslCommand,
  rotatePicture,
  switchDefinition,
  setWeatherEffect,
  showAnimation,
  showBalloonIcon,
  showChoices,
  showPicture,
  selectItem,
  script,
  scriptInput,
  scrollMap,
  setMovementRoute,
  setEventLocation,
  setVehicleLocation,
  skillRef,
  showScrollingText,
  showText,
  shakeScreen,
  shopProcessing,
  stateRef,
  tintPicture,
  tintScreen,
  variableDefinition,
  wait,
  switchRef,
  transferPlayer,
  troopRef,
  variableRef,
  weaponRef,
  isAssetReference,
  isProjectDataReference,
  isRuntimeSelector,
  isScriptInput,
} from "./dsl.js";

export type {
  AssetReference,
  BalloonIcon,
  AudioAssetFolder,
  AudioAssetReference,
  AudioPayload,
  ChangePlayerFollowersDslCommand,
  BattleProcessingDslCommand,
  BreakLoopDslCommand,
  ChangeArmorsDslCommand,
  ChangeGoldDslCommand,
  ChangeItemsDslCommand,
  ChangePartyMemberDslCommand,
  ChangeTransparencyDslCommand,
  ChangeWeaponsDslCommand,
  ColorInput,
  CommentDslCommand,
  CommonEventDslCommand,
  CommonEventDefinition,
  CommonEventTrigger,
  CommandOperand,
  CommandPosition,
  ControlVariablesGameDataOperand,
  ConditionalBranchCondition,
  ConditionalDslCommand,
  ConditionalVariableOperator,
  ControlSelfSwitchDslCommand,
  ControlSwitchesDslCommand,
  ControlTimerDslCommand,
  ControlVariablesDslCommand,
  DirectPosition,
  DslOwnedDeclaration,
  DslCommand,
  EraseEventDslCommand,
  ErasePictureDslCommand,
  EventDefinition,
  EventLocationDestination,
  EventPage,
  ExitEventDslCommand,
  FadeinScreenDslCommand,
  FadeoutScreenDslCommand,
  FlashScreenDslCommand,
  GatherFollowersDslCommand,
  GetOnOffVehicleDslCommand,
  ImageAssetFolder,
  ImageAssetReference,
  InputNumberDslCommand,
  JumpToLabelDslCommand,
  LabelDslCommand,
  LoopDslCommand,
  MapEventDefinition,
  MapDestination,
  MapPageTrigger,
  MovieAssetReference,
  MoveRouteCommand,
  NumericRange,
  OperateValueInput,
  PageConditions,
  PictureDisplayInput,
  PictureOrigin,
  PicturePosition,
  PluginDslCommand,
  RawDslCommand,
  RandomOperand,
  ReferenceKind,
  ReferenceRange,
  ReferenceValue,
  RuntimeSelector,
  CharacterRuntimeSelector,
  Direction,
  ScriptInput,
  ScriptOperand,
  ScrollMapDslCommand,
  ScriptDslCommand,
  SelectItemDslCommand,
  SetEventLocationDslCommand,
  SetMovementRouteDslCommand,
  SetVehicleLocationDslCommand,
  SetWeatherEffectDslCommand,
  ShakeScreenDslCommand,
  ShopProcessingDslCommand,
  ShowChoicesDslCommand,
  ShowAnimationDslCommand,
  ShowBalloonIconDslCommand,
  ShowPictureDslCommand,
  ShowScrollingTextDslCommand,
  ShowTextDslCommand,
  TintPictureDslCommand,
  TintScreenDslCommand,
  ToneInput,
  SwitchDefinition,
  TransferPlayerDslCommand,
  VariableOperand,
  VariablePosition,
  VariableDefinition,
  VehicleTarget,
  WaitDslCommand,
  WeatherEffectType,
  MovePictureDslCommand,
  RotatePictureDslCommand,
} from "./dsl.js";
export { discoverDefinitionFiles } from "./definitions.js";
export type { DefinitionSourceDiscovery } from "./definitions.js";
export type {
  CommandInputPrimitiveInspection,
  DuplicateAwareNameIndex,
  ReferenceEntry,
  ReferenceResolver,
  SnapshotReferenceSource,
  SnapshotReferenceInput,
  StagedDataGraph,
  ValidationIssue,
  ValidationResult,
} from "./staged-graph.js";
export { inspectCommandInputPrimitives } from "./staged-graph.js";
export type {
  CompileWorkspaceOptions,
  PushWorkspaceOptions,
  WorkspaceCommandOptions,
} from "./workflow.js";
export type { LoadedWorkspace, WorkspaceConfig } from "./workspace.js";

export type RuntimeBaseline = typeof runtimeBaseline;
