export const runtimeBaseline = {
  language: "typescript-strict",
  moduleSystem: "esm-nodenext",
  packageManager: "pnpm",
  runtime: "node-22-lts",
} as const;

export { loadWorkspace } from "./workspace.js";
export { loadDefinitionFile } from "./definitions.js";
export {
  cloneWorkspace,
  compileWorkspace,
  decompileWorkspace,
  diffWorkspace,
  isGeneratedProjectDataFresh,
  pullWorkspace,
  pushWorkspace,
} from "./workflow.js";
export {
  buildDuplicateAwareNameIndex,
  buildSnapshotReferenceInput,
  buildStagedDataGraph,
  validateDslOwnedDeclarations,
  validateStagedDataGraph,
} from "./staged-graph.js";
export {
  actorRef,
  audioAsset,
  armorRef,
  breakLoop,
  battleProcessing,
  changeArmors,
  changeGold,
  changeItems,
  changePartyMember,
  changeWeapons,
  classRef,
  comment,
  commonEvent,
  callCommonEvent,
  collectDslOwnedDeclarations,
  commonEventRef,
  controlSelfSwitch,
  controlSwitches,
  controlTimer,
  controlVariables,
  eraseEvent,
  conditional,
  exitEvent,
  getOnOffVehicle,
  imageAsset,
  inputNumber,
  itemRef,
  jumpToLabel,
  label,
  loop,
  mapEvent,
  mapRef,
  page,
  pluginCommand,
  movieAsset,
  rawDslCommand,
  switchDefinition,
  showChoices,
  selectItem,
  script,
  scriptInput,
  scrollMap,
  setEventLocation,
  setVehicleLocation,
  skillRef,
  showScrollingText,
  showText,
  shopProcessing,
  stateRef,
  variableDefinition,
  wait,
  switchRef,
  transferPlayer,
  troopRef,
  variableRef,
  weaponRef,
  isAssetReference,
  isProjectDataReference,
  isRuntimeSelector,
  isScriptInput,
} from "./dsl.js";

export type {
  AssetReference,
  AudioAssetFolder,
  AudioAssetReference,
  AudioPayload,
  BattleProcessingDslCommand,
  BreakLoopDslCommand,
  ChangeArmorsDslCommand,
  ChangeGoldDslCommand,
  ChangeItemsDslCommand,
  ChangePartyMemberDslCommand,
  ChangeWeaponsDslCommand,
  ColorInput,
  CommentDslCommand,
  CommonEventDslCommand,
  CommonEventDefinition,
  CommonEventTrigger,
  CommandOperand,
  CommandPosition,
  ControlVariablesGameDataOperand,
  ConditionalBranchCondition,
  ConditionalDslCommand,
  ConditionalVariableOperator,
  ControlSelfSwitchDslCommand,
  ControlSwitchesDslCommand,
  ControlTimerDslCommand,
  ControlVariablesDslCommand,
  DirectPosition,
  DslOwnedDeclaration,
  DslCommand,
  EraseEventDslCommand,
  EventDefinition,
  EventLocationDestination,
  EventPage,
  ExitEventDslCommand,
  GetOnOffVehicleDslCommand,
  ImageAssetFolder,
  ImageAssetReference,
  InputNumberDslCommand,
  JumpToLabelDslCommand,
  LabelDslCommand,
  LoopDslCommand,
  MapEventDefinition,
  MapDestination,
  MapPageTrigger,
  MovieAssetReference,
  NumericRange,
  OperateValueInput,
  PageConditions,
  PluginDslCommand,
  RawDslCommand,
  RandomOperand,
  ReferenceKind,
  ReferenceRange,
  ReferenceValue,
  RuntimeSelector,
  CharacterRuntimeSelector,
  Direction,
  ScriptInput,
  ScriptOperand,
  ScrollMapDslCommand,
  ScriptDslCommand,
  SelectItemDslCommand,
  SetEventLocationDslCommand,
  SetVehicleLocationDslCommand,
  ShopProcessingDslCommand,
  ShowChoicesDslCommand,
  ShowScrollingTextDslCommand,
  ShowTextDslCommand,
  ToneInput,
  SwitchDefinition,
  TransferPlayerDslCommand,
  VariableOperand,
  VariablePosition,
  VariableDefinition,
  VehicleTarget,
  WaitDslCommand,
} from "./dsl.js";
export { discoverDefinitionFiles } from "./definitions.js";
export type { DefinitionSourceDiscovery } from "./definitions.js";
export type {
  CommandInputPrimitiveInspection,
  DuplicateAwareNameIndex,
  ReferenceEntry,
  ReferenceResolver,
  SnapshotReferenceSource,
  SnapshotReferenceInput,
  StagedDataGraph,
  ValidationIssue,
  ValidationResult,
} from "./staged-graph.js";
export { inspectCommandInputPrimitives } from "./staged-graph.js";
export type {
  CompileWorkspaceOptions,
  PushWorkspaceOptions,
  WorkspaceCommandOptions,
} from "./workflow.js";
export type { LoadedWorkspace, WorkspaceConfig } from "./workspace.js";

export type RuntimeBaseline = typeof runtimeBaseline;
