export const runtimeBaseline = {
  language: "typescript-strict",
  moduleSystem: "esm-nodenext",
  packageManager: "pnpm",
  runtime: "node-22-lts",
} as const;

export { loadWorkspace } from "./workspace.js";
export { loadDefinitionFile } from "./definitions.js";
export {
  cloneWorkspace,
  compileWorkspace,
  decompileWorkspace,
  diffWorkspace,
  isGeneratedProjectDataFresh,
  pullWorkspace,
  pushWorkspace,
} from "./workflow.js";
export {
  buildDuplicateAwareNameIndex,
  buildSnapshotReferenceInput,
  buildStagedDataGraph,
  validateDslOwnedDeclarations,
  validateStagedDataGraph,
} from "./staged-graph.js";
export {
  actorRef,
  armorRef,
  breakLoop,
  battleProcessing,
  changeGold,
  changeItem,
  comment,
  commonEvent,
  callCommonEvent,
  collectDslOwnedDeclarations,
  commonEventRef,
  controlSelfSwitch,
  controlSwitch,
  controlVariable,
  eraseEvent,
  conditional,
  exitEvent,
  itemRef,
  jumpToLabel,
  label,
  loop,
  mapEvent,
  mapRef,
  page,
  pluginCommand,
  rawDslCommand,
  switchDefinition,
  showChoices,
  script,
  showText,
  variableDefinition,
  wait,
  switchRef,
  troopRef,
  variableRef,
  weaponRef,
} from "./dsl.js";

export type {
  BattleProcessingDslCommand,
  BreakLoopDslCommand,
  ChangeGoldDslCommand,
  ChangeItemDslCommand,
  CommentDslCommand,
  CommonEventDslCommand,
  CommonEventDefinition,
  CommonEventTrigger,
  ConditionalDslCommand,
  ControlSelfSwitchDslCommand,
  ControlSwitchDslCommand,
  ControlVariableDslCommand,
  DslOwnedDeclaration,
  DslCommand,
  EraseEventDslCommand,
  EventDefinition,
  EventPage,
  ExitEventDslCommand,
  JumpToLabelDslCommand,
  LabelDslCommand,
  LoopDslCommand,
  MapEventDefinition,
  MapPageTrigger,
  PageConditions,
  PluginDslCommand,
  RawDslCommand,
  ReferenceKind,
  ReferenceValue,
  ScriptDslCommand,
  ShopProcessingDslCommand,
  ShowChoicesDslCommand,
  ShowTextDslCommand,
  SwitchDefinition,
  TransferPlayerDslCommand,
  VariableDefinition,
  WaitDslCommand,
} from "./dsl.js";
export { discoverDefinitionFiles } from "./definitions.js";
export type { DefinitionSourceDiscovery } from "./definitions.js";
export type {
  DuplicateAwareNameIndex,
  ReferenceEntry,
  ReferenceResolver,
  SnapshotReferenceSource,
  SnapshotReferenceInput,
  StagedDataGraph,
  ValidationIssue,
  ValidationResult,
} from "./staged-graph.js";
export type {
  CompileWorkspaceOptions,
  PushWorkspaceOptions,
  WorkspaceCommandOptions,
} from "./workflow.js";
export type { LoadedWorkspace, WorkspaceConfig } from "./workspace.js";

export type RuntimeBaseline = typeof runtimeBaseline;
