export const runtimeBaseline = {
  language: "typescript-strict",
  moduleSystem: "esm-nodenext",
  packageManager: "pnpm",
  runtime: "node-22-lts",
} as const;

export { loadWorkspace } from "./workspace.js";
export { loadProject, buildProjectIndex, parseCommonEvents, parseMapInfos } from "./project.js";
export { loadDefinitionFile } from "./definitions.js";
export {
  actorRef,
  armorRef,
  breakLoop,
  battleProcessing,
  changeGold,
  changeItem,
  collectEventDefinitions,
  comment,
  commonEvent,
  callCommonEvent,
  commonEventRef,
  controlSelfSwitch,
  controlSwitch,
  controlVariable,
  eraseEvent,
  conditional,
  exitEvent,
  itemRef,
  jumpToLabel,
  label,
  loop,
  mapEvent,
  mapRef,
  page,
  pluginCommand,
  rawDslCommand,
  showChoices,
  script,
  showText,
  wait,
  switchRef,
  troopRef,
  variableRef,
  weaponRef,
} from "./dsl.js";

export type {
  BattleProcessingDslCommand,
  BreakLoopDslCommand,
  ChangeGoldDslCommand,
  ChangeItemDslCommand,
  CommentDslCommand,
  CommonEventDslCommand,
  CommonEventDefinition,
  CommonEventTrigger,
  ConditionalDslCommand,
  ControlSelfSwitchDslCommand,
  ControlSwitchDslCommand,
  ControlVariableDslCommand,
  DslCommand,
  EraseEventDslCommand,
  EventDefinition,
  EventPage,
  ExitEventDslCommand,
  JumpToLabelDslCommand,
  LabelDslCommand,
  LoopDslCommand,
  MapEventDefinition,
  MapPageTrigger,
  PageConditions,
  PluginDslCommand,
  ProjectIndex,
  RawDslCommand,
  ReferenceKind,
  ReferenceValue,
  ScriptDslCommand,
  ShopProcessingDslCommand,
  ShowChoicesDslCommand,
  ShowTextDslCommand,
  TransferPlayerDslCommand,
  WaitDslCommand,
} from "./dsl.js";
export type {
  DefinitionBinding,
  DefinitionTarget,
  LoadedWorkspace,
  WorkspaceConfig,
} from "./workspace.js";

export type RuntimeBaseline = typeof runtimeBaseline;
